'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace UF.Research.Authentication.Shibboleth

    Partial Public Class ViewRoleMappings

        '''<summary>
        '''pnlAddTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddTask As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''RadGrid1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadGrid1 As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''btnUpdateRoleMappings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateRoleMappings As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
